# spring.data.mongodb.uri=mongodb+srv://guptayashprogrammer_db_user:mongopassward@cluster0.8staqwd.mongodb.net/journaldb?appName=Cluster0
spring:
  data:
   mongodb:
     host: localhost
     port: 27017
     database: journaldb
     auto-index-creation: true


server:
  port: 8081
