# spring.data.mongodb.uri=mongodb+srv://guptayashprogrammer_db_user:mongopassward@cluster0.8staqwd.mongodb.net/journaldb?appName=Cluster0

spring.data.mongodb.uri=mongodb://localhost:27017/journaldb
spring.data.mongodb.auto-index-creation=true
# Enable debug logging for Spring Security
logging.level.org.springframework.security=DEBUG